# Generated by Django 6.0.6 on 2026-06-06 20:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django.contrib.gis.db.models.fields.LineStringField(help_text='Route path as LineString (GeoJSON) from pickup to dropoff', srid=4326)),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('duration', models.IntegerField(help_text='Estimated duration in seconds')),
                ('route_provider', models.CharField(choices=[('osrm', 'OSRM - Open Source Routing Machine'), ('osm', 'OpenStreetMap'), ('vroom', 'Vroom')], default='osrm', help_text='Free routing service used', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.OneToOneField(help_text='Associated ride', on_delete=django.db.models.deletion.CASCADE, related_name='route', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['-created_at'],
            },
        ),
    ]
