# Generated by Django 6.0.6 on 2026-06-28 17:44

import accounts.managers
import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('client', 'Client'), ('driver', 'Driver'), ('staff', 'Staff')], default='client', help_text='User role for access control', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Last login IP address', null=True)),
                ('oauth2_provider', models.CharField(blank=True, help_text='OAuth2 provider (google, github, etc.)', max_length=50)),
                ('oauth2_id', models.CharField(blank=True, help_text='External provider user ID', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', accounts.managers.EmailUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Empty'), (1, 'Male'), (2, 'Female')], default=0)),
                ('date_birth', models.DateField(blank=True, default=datetime.date(2008, 7, 2), null=True)),
            ],
            options={
                'verbose_name': 'Profile Client',
                'verbose_name_plural': 'Profiles Client',
                'default_related_name': 'clientprofile',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Empty'), (1, 'Male'), (2, 'Female')], default=0)),
                ('date_birth', models.DateField(blank=True, default=datetime.date(2008, 7, 2), null=True)),
                ('is_child_friendly', models.BooleanField(default=False, help_text='Driver accepts children')),
                ('is_pet_friendly', models.BooleanField(default=False, help_text='Driver accepts pets')),
                ('is_smoke_friendly', models.BooleanField(default=False, help_text='Smoking is allowed in vehicle')),
                ('is_music_friendly', models.BooleanField(default=True, help_text='Driver plays music during rides')),
                ('is_talking_friendly', models.BooleanField(default=True, help_text='Driver is open to conversation')),
                ('has_charger', models.BooleanField(default=False, help_text='Vehicle has phone charger')),
                ('has_aux', models.BooleanField(default=False, help_text='Vehicle has aux cable for music')),
                ('is_verified', models.BooleanField(default=False, help_text='Driver is verified')),
                ('is_active_driver', models.BooleanField(default=True, help_text='Driver is currently active')),
            ],
            options={
                'verbose_name': 'Profile Driver',
                'verbose_name_plural': 'Profiles Driver',
                'default_related_name': 'driverprofile',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Empty'), (1, 'Male'), (2, 'Female')], default=0)),
                ('date_birth', models.DateField(blank=True, default=datetime.date(2008, 7, 2), null=True)),
            ],
            options={
                'verbose_name': 'Profile Staff',
                'verbose_name_plural': 'Profiles Staff',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
    ]
