# Generated by Django 6.0.6 on 2026-06-27 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2008, 7, 2), null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2008, 7, 2), null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2008, 7, 2), null=True),
        ),
    ]
