# Generated by Django 6.0.6 on 2026-06-28 17:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(blank=True, help_text='Pickup location address', max_length=255)),
                ('dropoff_address', models.CharField(blank=True, help_text='Dropoff location address', max_length=255)),
                ('pickup_position', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Pickup location coordinates', null=True, srid=4326)),
                ('dropoff_position', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Dropoff location coordinates', null=True, srid=4326)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Ride price', max_digits=10, null=True)),
                ('distance', models.FloatField(blank=True, help_text='Estimated distance in km', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests')),
                ('is_empty', models.BooleanField(default=True, help_text='Ride is empty (no driver assigned yet)')),
                ('is_finished', models.BooleanField(default=False, help_text='Ride is finished')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the ride', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the ride started', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the ride finished', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who requested the ride', on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='accounts.clientprofile')),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this ride', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='accounts.driverprofile')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Vehicle used for this ride', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('history', models.JSONField(blank=True, default=dict, help_text="GeoJSON: {'type': 'FeatureCollection', 'features': [...]}")),
                ('speed_min', models.FloatField(blank=True, help_text='Minimum speed in km/h', null=True)),
                ('speed_avg', models.FloatField(blank=True, help_text='Average speed in km/h', null=True)),
                ('speed_max', models.FloatField(blank=True, help_text='Maximum speed in km/h', null=True)),
                ('speed_last', models.FloatField(blank=True, help_text='Last speed in km/h', null=True)),
                ('altitude_min', models.FloatField(blank=True, help_text='Minimum altitude in km', null=True)),
                ('altitude_avg', models.FloatField(blank=True, help_text='Average altitude in km', null=True)),
                ('altitude_max', models.FloatField(blank=True, help_text='Maximum altitude in km', null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driverprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_shipments', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RideRoute',
            fields=[
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rides.ride')),
                ('history', models.JSONField(blank=True, default=dict, help_text="GeoJSON: {'type': 'FeatureCollection', 'features': [...]}")),
                ('speed_min', models.FloatField(blank=True, help_text='Minimum speed in km/h', null=True)),
                ('speed_avg', models.FloatField(blank=True, help_text='Average speed in km/h', null=True)),
                ('speed_max', models.FloatField(blank=True, help_text='Maximum speed in km/h', null=True)),
                ('speed_last', models.FloatField(blank=True, help_text='Last speed in km/h', null=True)),
                ('altitude_min', models.FloatField(blank=True, help_text='Minimum altitude in km', null=True)),
                ('altitude_avg', models.FloatField(blank=True, help_text='Average altitude in km', null=True)),
                ('altitude_max', models.FloatField(blank=True, help_text='Maximum altitude in km', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Real distance in km', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Real duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Точний момент знімка')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('has_blown_tire', models.BooleanField(default=False, help_text='Whether the vehicle has a blown tire')),
                ('has_low_fuel', models.BooleanField(default=False, help_text='Whether the vehicle has low fuel')),
                ('speed', models.FloatField(help_text='Швидкість авто на момент знімка')),
                ('heading', models.FloatField(blank=True, help_text='Напрямок руху в градусах', null=True)),
                ('is_cargo_active', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_snapshots', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(help_text='Geographic position (latitude, longitude) in WGS84 format', srid=4326)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Current speed in km/h', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(help_text='Driver associated with this location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.driverprofile')),
                ('vehicle', models.ForeignKey(help_text='Vehicle associated with this location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['driver', '-updated_at'], name='rides_drive_driver__3ca963_idx'), models.Index(fields=['vehicle', '-updated_at'], name='rides_drive_vehicle_81de03_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['client', '-created_at'], name='rides_ride_client__cf3e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', '-created_at'], name='rides_ride_driver__2fafcd_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_ride_status_b1560e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletimesnapshot',
            index=models.Index(fields=['vehicle', '-timestamp'], name='rides_vehic_vehicle_a7f1e5_idx'),
        ),
    ]
