# Generated by Django 6.0.6 on 2026-06-06 20:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(help_text='Geographic position (latitude, longitude) in WGS84 format', srid=4326)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Current speed in km/h', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(help_text='Driver associated with this location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.driverprofile')),
                ('vehicle', models.ForeignKey(help_text='Vehicle associated with this location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['driver', '-updated_at'], name='rides_drive_driver__3ca963_idx'), models.Index(fields=['vehicle', '-updated_at'], name='rides_drive_vehicle_81de03_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(blank=True, help_text='Pickup location address', max_length=255)),
                ('dropoff_address', models.CharField(blank=True, help_text='Dropoff location address', max_length=255)),
                ('pickup_position', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Pickup location coordinates', null=True, srid=4326)),
                ('dropoff_position', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Dropoff location coordinates', null=True, srid=4326)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Ride price', max_digits=10, null=True)),
                ('distance', models.FloatField(blank=True, help_text='Estimated distance in km', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests')),
                ('is_empty', models.BooleanField(default=True, help_text='Ride is empty (no driver assigned yet)')),
                ('is_finished', models.BooleanField(default=False, help_text='Ride is finished')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the ride', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the ride started', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the ride finished', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who requested the ride', on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='accounts.clientprofile')),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this ride', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='accounts.driverprofile')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Vehicle used for this ride', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='rides_ride_client__cf3e1a_idx'), models.Index(fields=['driver', '-created_at'], name='rides_ride_driver__2fafcd_idx'), models.Index(fields=['status'], name='rides_ride_status_b1560e_idx')],
            },
        ),
    ]
