# Generated by Django 6.0.6 on 2026-06-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='speed_cur',
        ),
        migrations.AddField(
            model_name='ride',
            name='history',
            field=models.JSONField(blank=True, default=dict, help_text="GeoJSON: {'type': 'FeatureCollection', 'features': [...]}"),
        ),
    ]
