# Generated by Django 6.0.6 on 2026-06-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_remove_ride_speed_cur_ride_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRoute',
            fields=[
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rides.ride')),
                ('history', models.JSONField(blank=True, default=dict, help_text="GeoJSON: {'type': 'FeatureCollection', 'features': [...]}")),
                ('speed_min', models.FloatField(blank=True, help_text='Minimum speed in km/h', null=True)),
                ('speed_avg', models.FloatField(blank=True, help_text='Average speed in km/h', null=True)),
                ('speed_max', models.FloatField(blank=True, help_text='Maximum speed in km/h', null=True)),
                ('speed_last', models.FloatField(blank=True, help_text='Last speed in km/h', null=True)),
                ('altitude_min', models.FloatField(blank=True, help_text='Minimum altitude in km', null=True)),
                ('altitude_avg', models.FloatField(blank=True, help_text='Average altitude in km', null=True)),
                ('altitude_max', models.FloatField(blank=True, help_text='Maximum altitude in km', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Real distance in km', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Real duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ride',
            name='speed_avg',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='speed_max',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='speed_min',
        ),
    ]
