# Generated by Django 6.0.6 on 2026-06-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_rideroute_remove_ride_speed_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the ride', max_length=20),
        ),
    ]
