# Generated by Django 6.0.6 on 2026-06-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_ride_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='history',
        ),
    ]
