# Generated by Django 6.0.6 on 2026-06-28 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ride_history'),
        ('vehicles', '0002_remove_vehicle_speed_min_vehicle_has_been_lost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_shipments', to='vehicles.vehicle')),
            ],
        ),
    ]
