# Generated by Django 6.0.6 on 2026-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_cargoshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoshipment',
            name='altitude_avg',
            field=models.FloatField(blank=True, help_text='Average altitude in km', null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='altitude_max',
            field=models.FloatField(blank=True, help_text='Maximum altitude in km', null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='altitude_min',
            field=models.FloatField(blank=True, help_text='Minimum altitude in km', null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='history',
            field=models.JSONField(blank=True, default=dict, help_text="GeoJSON: {'type': 'FeatureCollection', 'features': [...]}"),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='speed_avg',
            field=models.FloatField(blank=True, help_text='Average speed in km/h', null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='speed_last',
            field=models.FloatField(blank=True, help_text='Last speed in km/h', null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='speed_max',
            field=models.FloatField(blank=True, help_text='Maximum speed in km/h', null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='speed_min',
            field=models.FloatField(blank=True, help_text='Minimum speed in km/h', null=True),
        ),
    ]
