# Generated by Django 6.0.6 on 2026-06-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientprofile_date_birth_and_more'),
        ('rides', '0007_cargoshipment_altitude_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoshipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driverprofile'),
        ),
    ]
