# Generated by Django 6.0.6 on 2026-06-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_cargoshipment_driver'),
        ('vehicles', '0002_remove_vehicle_speed_min_vehicle_has_been_lost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Точний момент знімка')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('has_blown_tire', models.BooleanField(default=False, help_text='Whether the vehicle has a blown tire')),
                ('has_low_fuel', models.BooleanField(default=False, help_text='Whether the vehicle has low fuel')),
                ('speed', models.FloatField(help_text='Швидкість авто на момент знімка')),
                ('heading', models.FloatField(blank=True, help_text='Напрямок руху в градусах', null=True)),
                ('is_cargo_active', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_snapshots', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='rides_vehic_vehicle_a7f1e5_idx')],
            },
        ),
    ]
