# Generated by Django 6.0.6 on 2026-06-28 08:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_vehicletimesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoshipment',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
