"""
Django settings for uber_django_leaflet project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
import platform

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- WINDOWS GDAL CONFIGURATION START ---
if platform.system() == 'Windows':
    OSGEO4W_ROOT = r"C:\OSGeo4W"
    GDAL_BIN = os.path.join(OSGEO4W_ROOT, 'bin')
    
    if os.path.exists(GDAL_BIN):
        # Add to Windows PATH environment variable for subprocesses
        os.environ['PATH'] = GDAL_BIN + os.pathsep + os.environ['PATH']
        
        # Add to Python system paths
        sys.path.insert(0, GDAL_BIN)
        
        # Register DLL directory for Python 3.8+ 
        if hasattr(os, 'add_dll_directory'):
            try:
                os.add_dll_directory(GDAL_BIN)
            except OSError:
                pass
        
        # Dynamically find the actual gdal*.dll file to prevent FileNotFoundError
        import glob
        gdal_files = glob.glob(os.path.join(GDAL_BIN, 'gdal*.dll'))
        if gdal_files:
            # Matches gdal.dll, gdal308.dll, gdal310.dll etc.
            GDAL_LIBRARY_PATH = gdal_files[0]
        else:
            GDAL_LIBRARY_PATH = os.path.join(GDAL_BIN, 'gdal.dll')
            
        GEOS_LIBRARY_PATH = os.path.join(GDAL_BIN, 'geos_c.dll')
# --- WINDOWS GDAL CONFIGURATION END ---


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mvl6t2wotee@cu6z1q#)p*%4ycnuyte^6%&_1o09v*-h)s66c_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.gis',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'oauth2_provider',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'leaflet',
    'django_bootstrap5',
    'corsheaders',
    'django_vite',

    # Local apps
    'accounts.apps.AccountsConfig',
    'vehicles',
    'rides',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'uber_django_leaflet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ASGI WSGI
WSGI_APPLICATION = 'uber_django_leaflet.wsgi.application'
ASGI_APPLICATION = 'uber_django_leaflet.asgi.application'

# Database configuration modified for hybrid local/docker development
# Inside Docker container, POSTGRES_HOST env var is 'db'.
# Outside Docker (local machine), it connects to localhost (127.0.0.1) where Docker maps port 5432.

DB_HOST = os.environ.get('POSTGRES_HOST', '127.0.0.1')

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DJANGO_DB_ENGINE', 'django.contrib.gis.db.backends.postgis'),
        'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': DB_HOST,
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# Django Channels configuration TESTING PURPOSES
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

LOGIN_REDIRECT_URL = '/taxi/'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Django REST Framework + OAuth2 (django-oauth-toolkit)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# drf-spectacular OpenAPI settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Uber Django Leaflet API',
    'DESCRIPTION': 'OpenAPI schema for the demo taxi project',
    'VERSION': '1.0.0',
    'CONTACT': {'name': 'API Support'},
}

# django-leaflet config
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (51.505, -0.09),
    'DEFAULT_ZOOM': 13,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'ATTRIBUTION_PREFIX': 'Map data © OpenStreetMap contributors',
}

# Fallback for containerized environments if not set above
if 'GDAL_LIBRARY_PATH' not in locals():
    GDAL_LIBRARY_PATH = os.environ.get('GDAL_LIBRARY_PATH', None)

# CORS settings - allow browser AJAX from any origin for demo/dev
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "assets"]

DJANGO_VITE = {
    "default": {
        "dev_mode": True,
        "manifest_path": BASE_DIR / "static" / "dist" / "manifest.json",
    }
}

DJANGO_VITE_DEV_SERVER_HOST = 'localhost'
DJANGO_VITE_DEV_SERVER_PORT = 5173