# Generated by Django 6.0.6 on 2026-06-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Vehicle brand (e.g., Toyota, Honda)', max_length=100)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Camry, Accord)', max_length=100)),
                ('color', models.CharField(help_text='Vehicle color', max_length=50)),
                ('license_plate', models.CharField(help_text='License plate number', max_length=20, unique=True)),
                ('year', models.IntegerField(help_text='Year of manufacture')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('van', 'Van'), ('truck', 'Truck')], default='sedan', help_text='Type of vehicle', max_length=20)),
                ('capacity', models.IntegerField(default=4, help_text='Number of passengers the vehicle can accommodate')),
                ('registration_date', models.DateField(help_text='Date of vehicle registration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the vehicle is active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether the vehicle is deleted')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the vehicle is available for rides')),
                ('is_emergency', models.BooleanField(default=False, help_text='Whether the vehicle is in emergency state')),
                ('has_blown_tire', models.BooleanField(default=False, help_text='Whether the vehicle has a blown tire')),
                ('has_low_fuel', models.BooleanField(default=False, help_text='Whether the vehicle has low fuel')),
                ('has_been_lost', models.BooleanField(default=False, help_text='Whether the vehicle has been lost')),
                ('speed_max', models.FloatField(blank=True, help_text='Maximum speed in km/h', null=True)),
                ('speed_last', models.FloatField(blank=True, help_text='Last recorded speed in km/h', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Driver who owns this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='accounts.driverprofile')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
