# Generated by Django 6.0.6 on 2026-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='speed_min',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_been_lost',
            field=models.BooleanField(default=False, help_text='Whether the vehicle has been lost'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_blown_tire',
            field=models.BooleanField(default=False, help_text='Whether the vehicle has a blown tire'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_low_fuel',
            field=models.BooleanField(default=False, help_text='Whether the vehicle has low fuel'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Whether the vehicle is in emergency state'),
        ),
    ]
